package eng.ahmed.test

data class Person(
    val address: String,
    val birth_data: String,
    val blood: String,
    val bonus: Int,
    val cardexpir: String,
    val color: String,
    val company: String,
    val domain: String,
    val domain_url: String,
    val email_d: String,
    val email_u: String,
    val email_url: String,
    val eye: String,
    val hair: String,
    val height: Int,
    val ipv4: String,
    val ipv4_url: String,
    val latitude: Double,
    val longitude: Double,
    val macaddress: String,
    val maiden_name: String,
    val name: String,
    val password: String,
    val phone_h: String,
    val phone_w: String,
    val pict: String,
    val plasticcard: String,
    val sport: String,
    val url: String,
    val useragent: String,
    val username: String,
    val uuid: String,
    val weight: Double
)